#!/bin/zsh

mv -v poke1.gif bulbasaur.gif
mv -v poke2.gif ivysaur.gif
mv -v poke3.gif venusaur.gif
mv -v poke4.gif charmander.gif
mv -v poke5.gif charmeleon.gif
mv -v poke6.gif charizard.gif
mv -v poke7.gif squirtle.gif
mv -v poke8.gif wartortle.gif
mv -v poke9.gif blastoise.gif
mv -v poke10.gif caterpie.gif
mv -v poke11.gif metapod.gif
mv -v poke12.gif butterfree.gif
mv -v poke13.gif weedle.gif
mv -v poke14.gif kakuna.gif
mv -v poke15.gif beedrill.gif
mv -v poke16.gif pidgey.gif
mv -v poke17.gif pidgeotto.gif
mv -v poke18.gif pidgeot.gif
mv -v poke19.gif rattata.gif
mv -v poke20.gif raticate.gif
mv -v poke21.gif spearow.gif
mv -v poke22.gif fearow.gif
mv -v poke23.gif ekans.gif
mv -v poke24.gif arbok.gif
mv -v poke25.gif pikachu.gif
mv -v poke26.gif raichu.gif
mv -v poke27.gif sandshrew.gif
mv -v poke28.gif sandslash.gif
mv -v poke29.gif nidoran♀.gif
mv -v poke30.gif nidorina.gif
mv -v poke31.gif nidoqueen.gif
mv -v poke32.gif nidoran♂.gif
mv -v poke33.gif nidorino.gif
mv -v poke34.gif nidoking.gif
mv -v poke35.gif clefairy.gif
mv -v poke36.gif clefable.gif
mv -v poke37.gif vulpix.gif
mv -v poke38.gif ninetales.gif
mv -v poke39.gif jigglypuff.gif
mv -v poke40.gif wigglytuff.gif
mv -v poke41.gif zubat.gif
mv -v poke42.gif golbat.gif
mv -v poke43.gif oddish.gif
mv -v poke44.gif gloom.gif
mv -v poke45.gif vileplume.gif
mv -v poke46.gif paras.gif
mv -v poke47.gif parasect.gif
mv -v poke48.gif venonat.gif
mv -v poke49.gif venomoth.gif
mv -v poke50.gif diglett.gif
mv -v poke51.gif dugtrio.gif
mv -v poke52.gif meowth.gif
mv -v poke53.gif persian.gif
mv -v poke54.gif psyduck.gif
mv -v poke55.gif golduck.gif
mv -v poke56.gif mankey.gif
mv -v poke57.gif primeape.gif
mv -v poke58.gif growlithe.gif
mv -v poke59.gif arcanine.gif
mv -v poke60.gif poliwag.gif
mv -v poke61.gif poliwhirl.gif
mv -v poke62.gif poliwrath.gif
mv -v poke63.gif abra.gif
mv -v poke64.gif kadabra.gif
mv -v poke65.gif alakazam.gif
mv -v poke66.gif machop.gif
mv -v poke67.gif machoke.gif
mv -v poke68.gif machamp.gif
mv -v poke69.gif bellsprout.gif
mv -v poke70.gif weepinbell.gif
mv -v poke71.gif victreebel.gif
mv -v poke72.gif tentacool.gif
mv -v poke73.gif tentacruel.gif
mv -v poke74.gif geodude.gif
mv -v poke75.gif graveler.gif
mv -v poke76.gif golem.gif
mv -v poke77.gif ponyta.gif
mv -v poke78.gif rapidash.gif
mv -v poke79.gif slowpoke.gif
mv -v poke80.gif slowbro.gif
mv -v poke81.gif magnemite.gif
mv -v poke82.gif magneton.gif
mv -v poke83.gif farfetch’d.gif
mv -v poke84.gif doduo.gif
mv -v poke85.gif dodrio.gif
mv -v poke86.gif seel.gif
mv -v poke87.gif dewgong.gif
mv -v poke88.gif grimer.gif
mv -v poke89.gif muk.gif
mv -v poke90.gif shellder.gif
mv -v poke91.gif cloyster.gif
mv -v poke92.gif gastly.gif
mv -v poke93.gif haunter.gif
mv -v poke94.gif gengar.gif
mv -v poke95.gif onix.gif
mv -v poke96.gif drowzee.gif
mv -v poke97.gif hypno.gif
mv -v poke98.gif krabby.gif
mv -v poke99.gif kingler.gif
mv -v poke100.gif voltorb.gif
mv -v poke101.gif electrode.gif
mv -v poke102.gif exeggcute.gif
mv -v poke103.gif exeggutor.gif
mv -v poke104.gif cubone.gif
mv -v poke105.gif marowak.gif
mv -v poke106.gif hitmonlee.gif
mv -v poke107.gif hitmonchan.gif
mv -v poke108.gif lickitung.gif
mv -v poke109.gif koffing.gif
mv -v poke110.gif weezing.gif
mv -v poke111.gif rhyhorn.gif
mv -v poke112.gif rhydon.gif
mv -v poke113.gif chansey.gif
mv -v poke114.gif tangela.gif
mv -v poke115.gif kangaskhan.gif
mv -v poke116.gif horsea.gif
mv -v poke117.gif seadra.gif
mv -v poke118.gif goldeen.gif
mv -v poke119.gif seaking.gif
mv -v poke120.gif staryu.gif
mv -v poke121.gif starmie.gif
mv -v poke122.gif mr. mime.gif
mv -v poke123.gif scyther.gif
mv -v poke124.gif jynx.gif
mv -v poke125.gif electabuzz.gif
mv -v poke126.gif magmar.gif
mv -v poke127.gif pinsir.gif
mv -v poke128.gif tauros.gif
mv -v poke129.gif magikarp.gif
mv -v poke130.gif gyarados.gif
mv -v poke131.gif lapras.gif
mv -v poke132.gif ditto.gif
mv -v poke133.gif eevee.gif
mv -v poke134.gif vaporeon.gif
mv -v poke135.gif jolteon.gif
mv -v poke136.gif flareon.gif
mv -v poke137.gif porygon.gif
mv -v poke138.gif omanyte.gif
mv -v poke139.gif omastar.gif
mv -v poke140.gif kabuto.gif
mv -v poke141.gif kabutops.gif
mv -v poke142.gif aerodactyl.gif
mv -v poke143.gif snorlax.gif
mv -v poke144.gif articuno.gif
mv -v poke145.gif zapdos.gif
mv -v poke146.gif moltres.gif
mv -v poke147.gif dratini.gif
mv -v poke148.gif dragonair.gif
mv -v poke149.gif dragonite.gif
mv -v poke150.gif mewtwo.gif
mv -v poke151.gif mew.gif
mv -v poke152.gif chikorita.gif
mv -v poke153.gif bayleef.gif
mv -v poke154.gif meganium.gif
mv -v poke155.gif cyndaquil.gif
mv -v poke156.gif quilava.gif
mv -v poke157.gif typhlosion.gif
mv -v poke158.gif totodile.gif
mv -v poke159.gif croconaw.gif
mv -v poke160.gif feraligatr.gif
mv -v poke161.gif sentret.gif
mv -v poke162.gif furret.gif
mv -v poke163.gif hoothoot.gif
mv -v poke164.gif noctowl.gif
mv -v poke165.gif ledyba.gif
mv -v poke166.gif ledian.gif
mv -v poke167.gif spinarak.gif
mv -v poke168.gif ariados.gif
mv -v poke169.gif crobat.gif
mv -v poke170.gif chinchou.gif
mv -v poke171.gif lanturn.gif
mv -v poke172.gif pichu.gif
mv -v poke173.gif cleffa.gif
mv -v poke174.gif igglybuff.gif
mv -v poke175.gif togepi.gif
mv -v poke176.gif togetic.gif
mv -v poke177.gif natu.gif
mv -v poke178.gif xatu.gif
mv -v poke179.gif mareep.gif
mv -v poke180.gif flaaffy.gif
mv -v poke181.gif ampharos.gif
mv -v poke182.gif bellossom.gif
mv -v poke183.gif marill.gif
mv -v poke184.gif azumarill.gif
mv -v poke185.gif sudowoodo.gif
mv -v poke186.gif politoed.gif
mv -v poke187.gif hoppip.gif
mv -v poke188.gif skiploom.gif
mv -v poke189.gif jumpluff.gif
mv -v poke190.gif aipom.gif
mv -v poke191.gif sunkern.gif
mv -v poke192.gif sunflora.gif
mv -v poke193.gif yanma.gif
mv -v poke194.gif wooper.gif
mv -v poke195.gif quagsire.gif
mv -v poke196.gif espeon.gif
mv -v poke197.gif umbreon.gif
mv -v poke198.gif murkrow.gif
mv -v poke199.gif slowking.gif
mv -v poke200.gif misdreavus.gif
mv -v poke201.gif unown.gif
mv -v poke202.gif wobbuffet.gif
mv -v poke203.gif girafarig.gif
mv -v poke204.gif pineco.gif
mv -v poke205.gif forretress.gif
mv -v poke206.gif dunsparce.gif
mv -v poke207.gif gligar.gif
mv -v poke208.gif steelix.gif
mv -v poke209.gif snubbull.gif
mv -v poke210.gif granbull.gif
mv -v poke211.gif qwilfish.gif
mv -v poke212.gif scizor.gif
mv -v poke213.gif shuckle.gif
mv -v poke214.gif heracross.gif
mv -v poke215.gif sneasel.gif
mv -v poke216.gif teddiursa.gif
mv -v poke217.gif ursaring.gif
mv -v poke218.gif slugma.gif
mv -v poke219.gif magcargo.gif
mv -v poke220.gif swinub.gif
mv -v poke221.gif piloswine.gif
mv -v poke222.gif corsola.gif
mv -v poke223.gif remoraid.gif
mv -v poke224.gif octillery.gif
mv -v poke225.gif delibird.gif
mv -v poke226.gif mantine.gif
mv -v poke227.gif skarmory.gif
mv -v poke228.gif houndour.gif
mv -v poke229.gif houndoom.gif
mv -v poke230.gif kingdra.gif
mv -v poke231.gif phanpy.gif
mv -v poke232.gif donphan.gif
mv -v poke233.gif porygon2.gif
mv -v poke234.gif stantler.gif
mv -v poke235.gif smeargle.gif
mv -v poke236.gif tyrogue.gif
mv -v poke237.gif hitmontop.gif
mv -v poke238.gif smoochum.gif
mv -v poke239.gif elekid.gif
mv -v poke240.gif magby.gif
mv -v poke241.gif miltank.gif
mv -v poke242.gif blissey.gif
mv -v poke243.gif raikou.gif
mv -v poke244.gif entei.gif
mv -v poke245.gif suicune.gif
mv -v poke246.gif larvitar.gif
mv -v poke247.gif pupitar.gif
mv -v poke248.gif tyranitar.gif
mv -v poke249.gif lugia.gif
mv -v poke250.gif ho-oh.gif
mv -v poke251.gif celebi.gif
mv -v poke252.gif treecko.gif
mv -v poke253.gif grovyle.gif
mv -v poke254.gif sceptile.gif
mv -v poke255.gif torchic.gif
mv -v poke256.gif combusken.gif
mv -v poke257.gif blaziken.gif
mv -v poke258.gif mudkip.gif
mv -v poke259.gif marshtomp.gif
mv -v poke260.gif swampert.gif
mv -v poke261.gif poochyena.gif
mv -v poke262.gif mightyena.gif
mv -v poke263.gif zigzagoon.gif
mv -v poke264.gif linoone.gif
mv -v poke265.gif wurmple.gif
mv -v poke266.gif silcoon.gif
mv -v poke267.gif beautifly.gif
mv -v poke268.gif cascoon.gif
mv -v poke269.gif dustox.gif
mv -v poke270.gif lotad.gif
mv -v poke271.gif lombre.gif
mv -v poke272.gif ludicolo.gif
mv -v poke273.gif seedot.gif
mv -v poke274.gif nuzleaf.gif
mv -v poke275.gif shiftry.gif
mv -v poke276.gif taillow.gif
mv -v poke277.gif swellow.gif
mv -v poke278.gif wingull.gif
mv -v poke279.gif pelipper.gif
mv -v poke280.gif ralts.gif
mv -v poke281.gif kirlia.gif
mv -v poke282.gif gardevoir.gif
mv -v poke283.gif surskit.gif
mv -v poke284.gif masquerain.gif
mv -v poke285.gif shroomish.gif
mv -v poke286.gif breloom.gif
mv -v poke287.gif slakoth.gif
mv -v poke288.gif vigoroth.gif
mv -v poke289.gif slaking.gif
mv -v poke290.gif nincada.gif
mv -v poke291.gif ninjask.gif
mv -v poke292.gif shedinja.gif
mv -v poke293.gif whismur.gif
mv -v poke294.gif loudred.gif
mv -v poke295.gif exploud.gif
mv -v poke296.gif makuhita.gif
mv -v poke297.gif hariyama.gif
mv -v poke298.gif azurill.gif
mv -v poke299.gif nosepass.gif
mv -v poke300.gif skitty.gif
mv -v poke301.gif delcatty.gif
mv -v poke302.gif sableye.gif
mv -v poke303.gif mawile.gif
mv -v poke304.gif aron.gif
mv -v poke305.gif lairon.gif
mv -v poke306.gif aggron.gif
mv -v poke307.gif meditite.gif
mv -v poke308.gif medicham.gif
mv -v poke309.gif electrike.gif
mv -v poke310.gif manectric.gif
mv -v poke311.gif plusle.gif
mv -v poke312.gif minun.gif
mv -v poke313.gif volbeat.gif
mv -v poke314.gif illumise.gif
mv -v poke315.gif roselia.gif
mv -v poke316.gif gulpin.gif
mv -v poke317.gif swalot.gif
mv -v poke318.gif carvanha.gif
mv -v poke319.gif sharpedo.gif
mv -v poke320.gif wailmer.gif
mv -v poke321.gif wailord.gif
mv -v poke322.gif numel.gif
mv -v poke323.gif camerupt.gif
mv -v poke324.gif torkoal.gif
mv -v poke325.gif spoink.gif
mv -v poke326.gif grumpig.gif
mv -v poke327.gif spinda.gif
mv -v poke328.gif trapinch.gif
mv -v poke329.gif vibrava.gif
mv -v poke330.gif flygon.gif
mv -v poke331.gif cacnea.gif
mv -v poke332.gif cacturne.gif
mv -v poke333.gif swablu.gif
mv -v poke334.gif altaria.gif
mv -v poke335.gif zangoose.gif
mv -v poke336.gif seviper.gif
mv -v poke337.gif lunatone.gif
mv -v poke338.gif solrock.gif
mv -v poke339.gif barboach.gif
mv -v poke340.gif whiscash.gif
mv -v poke341.gif corphish.gif
mv -v poke342.gif crawdaunt.gif
mv -v poke343.gif baltoy.gif
mv -v poke344.gif claydol.gif
mv -v poke345.gif lileep.gif
mv -v poke346.gif cradily.gif
mv -v poke347.gif anorith.gif
mv -v poke348.gif armaldo.gif
mv -v poke349.gif feebas.gif
mv -v poke350.gif milotic.gif
mv -v poke351.gif castform.gif
mv -v poke352.gif kecleon.gif
mv -v poke353.gif shuppet.gif
mv -v poke354.gif banette.gif
mv -v poke355.gif duskull.gif
mv -v poke356.gif dusclops.gif
mv -v poke357.gif tropius.gif
mv -v poke358.gif chimecho.gif
mv -v poke359.gif absol.gif
mv -v poke360.gif wynaut.gif
mv -v poke361.gif snorunt.gif
mv -v poke362.gif glalie.gif
mv -v poke363.gif spheal.gif
mv -v poke364.gif sealeo.gif
mv -v poke365.gif walrein.gif
mv -v poke366.gif clamperl.gif
mv -v poke367.gif huntail.gif
mv -v poke368.gif gorebyss.gif
mv -v poke369.gif relicanth.gif
mv -v poke370.gif luvdisc.gif
mv -v poke371.gif bagon.gif
mv -v poke372.gif shelgon.gif
mv -v poke373.gif salamence.gif
mv -v poke374.gif beldum.gif
mv -v poke375.gif metang.gif
mv -v poke376.gif metagross.gif
mv -v poke377.gif regirock.gif
mv -v poke378.gif regice.gif
mv -v poke379.gif registeel.gif
mv -v poke380.gif latias.gif
mv -v poke381.gif latios.gif
mv -v poke382.gif kyogre.gif
mv -v poke383.gif groudon.gif
mv -v poke384.gif rayquaza.gif
mv -v poke385.gif jirachi.gif
mv -v poke386.gif deoxys.gif
mv -v poke387.gif turtwig.gif
mv -v poke388.gif grotle.gif
mv -v poke389.gif torterra.gif
mv -v poke390.gif chimchar.gif
mv -v poke391.gif monferno.gif
mv -v poke392.gif infernape.gif
mv -v poke393.gif piplup.gif
mv -v poke394.gif prinplup.gif
mv -v poke395.gif empoleon.gif
mv -v poke396.gif starly.gif
mv -v poke397.gif staravia.gif
mv -v poke398.gif staraptor.gif
mv -v poke399.gif bidoof.gif
mv -v poke400.gif bibarel.gif
mv -v poke401.gif kricketot.gif
mv -v poke402.gif kricketune.gif
mv -v poke403.gif shinx.gif
mv -v poke404.gif luxio.gif
mv -v poke405.gif luxray.gif
mv -v poke406.gif budew.gif
mv -v poke407.gif roserade.gif
mv -v poke408.gif cranidos.gif
mv -v poke409.gif rampardos.gif
mv -v poke410.gif shieldon.gif
mv -v poke411.gif bastiodon.gif
mv -v poke412.gif burmy.gif
mv -v poke413.gif wormadam.gif
mv -v poke414.gif mothim.gif
mv -v poke415.gif combee.gif
mv -v poke416.gif vespiquen.gif
mv -v poke417.gif pachirisu.gif
mv -v poke418.gif buizel.gif
mv -v poke419.gif floatzel.gif
mv -v poke420.gif cherubi.gif
mv -v poke421.gif cherrim.gif
mv -v poke422.gif shellos.gif
mv -v poke423.gif gastrodon.gif
mv -v poke424.gif ambipom.gif
mv -v poke425.gif drifloon.gif
mv -v poke426.gif drifblim.gif
mv -v poke427.gif buneary.gif
mv -v poke428.gif lopunny.gif
mv -v poke429.gif mismagius.gif
mv -v poke430.gif honchkrow.gif
mv -v poke431.gif glameow.gif
mv -v poke432.gif purugly.gif
mv -v poke433.gif chingling.gif
mv -v poke434.gif stunky.gif
mv -v poke435.gif skuntank.gif
mv -v poke436.gif bronzor.gif
mv -v poke437.gif bronzong.gif
mv -v poke438.gif bonsly.gif
mv -v poke439.gif mime jr..gif
mv -v poke440.gif happiny.gif
mv -v poke441.gif chatot.gif
mv -v poke442.gif spiritomb.gif
mv -v poke443.gif gible.gif
mv -v poke444.gif gabite.gif
mv -v poke445.gif garchomp.gif
mv -v poke446.gif munchlax.gif
mv -v poke447.gif riolu.gif
mv -v poke448.gif lucario.gif
mv -v poke449.gif hippopotas.gif
mv -v poke450.gif hippowdon.gif
mv -v poke451.gif skorupi.gif
mv -v poke452.gif drapion.gif
mv -v poke453.gif croagunk.gif
mv -v poke454.gif toxicroak.gif
mv -v poke455.gif carnivine.gif
mv -v poke456.gif finneon.gif
mv -v poke457.gif lumineon.gif
mv -v poke458.gif mantyke.gif
mv -v poke459.gif snover.gif
mv -v poke460.gif abomasnow.gif
mv -v poke461.gif weavile.gif
mv -v poke462.gif magnezone.gif
mv -v poke463.gif lickilicky.gif
mv -v poke464.gif rhyperior.gif
mv -v poke465.gif tangrowth.gif
mv -v poke466.gif electivire.gif
mv -v poke467.gif magmortar.gif
mv -v poke468.gif togekiss.gif
mv -v poke469.gif yanmega.gif
mv -v poke470.gif leafeon.gif
mv -v poke471.gif glaceon.gif
mv -v poke472.gif gliscor.gif
mv -v poke473.gif mamoswine.gif
mv -v poke474.gif porygon-z.gif
mv -v poke475.gif gallade.gif
mv -v poke476.gif probopass.gif
mv -v poke477.gif dusknoir.gif
mv -v poke478.gif froslass.gif
mv -v poke479.gif rotom.gif
mv -v poke480.gif uxie.gif
mv -v poke481.gif mesprit.gif
mv -v poke482.gif azelf.gif
mv -v poke483.gif dialga.gif
mv -v poke484.gif palkia.gif
mv -v poke485.gif heatran.gif
mv -v poke486.gif regigigas.gif
mv -v poke487.gif giratina.gif
mv -v poke488.gif cresselia.gif
mv -v poke489.gif phione.gif
mv -v poke490.gif manaphy.gif
mv -v poke491.gif darkrai.gif
mv -v poke492.gif shaymin.gif
mv -v poke493.gif arceus.gif
mv -v poke494.gif victini.gif
mv -v poke495.gif snivy.gif
mv -v poke496.gif servine.gif
mv -v poke497.gif serperior.gif
mv -v poke498.gif tepig.gif
mv -v poke499.gif pignite.gif
mv -v poke500.gif emboar.gif
mv -v poke501.gif oshawott.gif
mv -v poke502.gif dewott.gif
mv -v poke503.gif samurott.gif
mv -v poke504.gif patrat.gif
mv -v poke505.gif watchog.gif
mv -v poke506.gif lillipup.gif
mv -v poke507.gif herdier.gif
mv -v poke508.gif stoutland.gif
mv -v poke509.gif purrloin.gif
mv -v poke510.gif liepard.gif
mv -v poke511.gif pansage.gif
mv -v poke512.gif simisage.gif
mv -v poke513.gif pansear.gif
mv -v poke514.gif simisear.gif
mv -v poke515.gif panpour.gif
mv -v poke516.gif simipour.gif
mv -v poke517.gif munna.gif
mv -v poke518.gif musharna.gif
mv -v poke519.gif pidove.gif
mv -v poke520.gif tranquill.gif
mv -v poke521.gif unfezant.gif
mv -v poke522.gif blitzle.gif
mv -v poke523.gif zebstrika.gif
mv -v poke524.gif roggenrola.gif
mv -v poke525.gif boldore.gif
mv -v poke526.gif gigalith.gif
mv -v poke527.gif woobat.gif
mv -v poke528.gif swoobat.gif
mv -v poke529.gif drilbur.gif
mv -v poke530.gif excadrill.gif
mv -v poke531.gif audino.gif
mv -v poke532.gif timburr.gif
mv -v poke533.gif gurdurr.gif
mv -v poke534.gif conkeldurr.gif
mv -v poke535.gif tympole.gif
mv -v poke536.gif palpitoad.gif
mv -v poke537.gif seismitoad.gif
mv -v poke538.gif throh.gif
mv -v poke539.gif sawk.gif
mv -v poke540.gif sewaddle.gif
mv -v poke541.gif swadloon.gif
mv -v poke542.gif leavanny.gif
mv -v poke543.gif venipede.gif
mv -v poke544.gif whirlipede.gif
mv -v poke545.gif scolipede.gif
mv -v poke546.gif cottonee.gif
mv -v poke547.gif whimsicott.gif
mv -v poke548.gif petilil.gif
mv -v poke549.gif lilligant.gif
mv -v poke550.gif basculin.gif
mv -v poke551.gif sandile.gif
mv -v poke552.gif krokorok.gif
mv -v poke553.gif krookodile.gif
mv -v poke554.gif darumaka.gif
mv -v poke555.gif darmanitan.gif
mv -v poke556.gif maractus.gif
mv -v poke557.gif dwebble.gif
mv -v poke558.gif crustle.gif
mv -v poke559.gif scraggy.gif
mv -v poke560.gif scrafty.gif
mv -v poke561.gif sigilyph.gif
mv -v poke562.gif yamask.gif
mv -v poke563.gif cofagrigus.gif
mv -v poke564.gif tirtouga.gif
mv -v poke565.gif carracosta.gif
mv -v poke566.gif archen.gif
mv -v poke567.gif archeops.gif
mv -v poke568.gif trubbish.gif
mv -v poke569.gif garbodor.gif
mv -v poke570.gif zorua.gif
mv -v poke571.gif zoroark.gif
mv -v poke572.gif minccino.gif
mv -v poke573.gif cinccino.gif
mv -v poke574.gif gothita.gif
mv -v poke575.gif gothorita.gif
mv -v poke576.gif gothitelle.gif
mv -v poke577.gif solosis.gif
mv -v poke578.gif duosion.gif
mv -v poke579.gif reuniclus.gif
mv -v poke580.gif ducklett.gif
mv -v poke581.gif swanna.gif
mv -v poke582.gif vanillite.gif
mv -v poke583.gif vanillish.gif
mv -v poke584.gif vanilluxe.gif
mv -v poke585.gif deerling.gif
mv -v poke586.gif sawsbuck.gif
mv -v poke587.gif emolga.gif
mv -v poke588.gif karrablast.gif
mv -v poke589.gif escavalier.gif
mv -v poke590.gif foongus.gif
mv -v poke591.gif amoonguss.gif
mv -v poke592.gif frillish.gif
mv -v poke593.gif jellicent.gif
mv -v poke594.gif alomomola.gif
mv -v poke595.gif joltik.gif
mv -v poke596.gif galvantula.gif
mv -v poke597.gif ferroseed.gif
mv -v poke598.gif ferrothorn.gif
mv -v poke599.gif klink.gif
mv -v poke600.gif klang.gif
mv -v poke601.gif klinklang.gif
mv -v poke602.gif tynamo.gif
mv -v poke603.gif eelektrik.gif
mv -v poke604.gif eelektross.gif
mv -v poke605.gif elgyem.gif
mv -v poke606.gif beheeyem.gif
mv -v poke607.gif litwick.gif
mv -v poke608.gif lampent.gif
mv -v poke609.gif chandelure.gif
mv -v poke610.gif axew.gif
mv -v poke611.gif fraxure.gif
mv -v poke612.gif haxorus.gif
mv -v poke613.gif cubchoo.gif
mv -v poke614.gif beartic.gif
mv -v poke615.gif cryogonal.gif
mv -v poke616.gif shelmet.gif
mv -v poke617.gif accelgor.gif
mv -v poke618.gif stunfisk.gif
mv -v poke619.gif mienfoo.gif
mv -v poke620.gif mienshao.gif
mv -v poke621.gif druddigon.gif
mv -v poke622.gif golett.gif
mv -v poke623.gif golurk.gif
mv -v poke624.gif pawniard.gif
mv -v poke625.gif bisharp.gif
mv -v poke626.gif bouffalant.gif
mv -v poke627.gif rufflet.gif
mv -v poke628.gif braviary.gif
mv -v poke629.gif vullaby.gif
mv -v poke630.gif mandibuzz.gif
mv -v poke631.gif heatmor.gif
mv -v poke632.gif durant.gif
mv -v poke633.gif deino.gif
mv -v poke634.gif zweilous.gif
mv -v poke635.gif hydreigon.gif
mv -v poke636.gif larvesta.gif
mv -v poke637.gif volcarona.gif
mv -v poke638.gif cobalion.gif
mv -v poke639.gif terrakion.gif
mv -v poke640.gif virizion.gif
mv -v poke641.gif tornadus.gif
mv -v poke642.gif thundurus.gif
mv -v poke643.gif reshiram.gif
mv -v poke644.gif zekrom.gif
mv -v poke645.gif landorus.gif
mv -v poke646.gif kyurem.gif
mv -v poke647.gif keldeo.gif
mv -v poke648.gif meloetta.gif
mv -v poke649.gif genesect.gif
